
package bnb.billing.system;

import java.sql.*;
import SQLManager.Connector;
import javax.swing.JOptionPane;

public class addProduct extends javax.swing.JFrame implements Interface {

    public addProduct() {
        initComponents();
    }
    
    public void clear() { // used for the clear all button
        txtProdName.setText("");
        txtRate.setText("");
        txtDesc.setText("");
        btnSave.setEnabled(false);
    }
        
    // takes method from interface 
    @Override
    public void backHomePage() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProdName = new javax.swing.JTextField();
        txtRate = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtProductID = new javax.swing.JLabel();
        txtYes = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 240));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProdName.setFont(new java.awt.Font("Moche", 0, 13)); // NOI18N
        getContentPane().add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 280, -1));

        txtRate.setFont(new java.awt.Font("Moche", 0, 13)); // NOI18N
        getContentPane().add(txtRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 280, -1));

        txtDesc.setFont(new java.awt.Font("Moche", 0, 13)); // NOI18N
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 280, -1));

        txtProductID.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtProductID.setForeground(new java.awt.Color(255, 0, 0));
        txtProductID.setText("100");
        getContentPane().add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 20));

        txtYes.setFont(new java.awt.Font("Moche", 0, 13)); // NOI18N
        txtYes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        txtYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYesActionPerformed(evt);
            }
        });
        getContentPane().add(txtYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 280, -1));

        btnSave.setFont(new java.awt.Font("Moche", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        btnClearAll.setFont(new java.awt.Font("Moche", 0, 14)); // NOI18N
        btnClearAll.setText("Clear All");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 390, 90, -1));

        btnClose.setFont(new java.awt.Font("Moche", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addProductWallP.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // when page shows up, product ID will immediately be updated to the latest and unused product ID
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            Connection con = Connector.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select max(pId) from product");
            if (rs.next()) {
                int id = rs.getInt(1);
                id = id + 1;
                String str = String.valueOf(id);
                txtProductID.setText(str);
            }
            else
                txtProductID.setText("1");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    // code for save button; when clicked, user input will be implemented to the SQL table 'product'
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String pId = txtProductID.getText();
        String pName = txtProdName.getText();
        String rate = txtRate.getText();
        String description = txtDesc.getText();
        String activate = (String)txtYes.getSelectedItem();
        clear();
        
        try {
            Connection con = Connector.getCon(); // connecting to the SQL connector in Connector.java
            
            PreparedStatement ps = con.prepareStatement("insert into product values(?,?,?,?,?)"); // applying the user input into the SQL 'product' database table
            ps.setString(1, pId);
            ps.setString(2, pName);
            ps.setString(3, rate);
            ps.setString(4, description);
            ps.setString(5, activate);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated!");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYesActionPerformed

    // resets the whole page
    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        setVisible(false);
        new addProduct().setVisible(true);
    }//GEN-LAST:event_btnClearAllActionPerformed

    // goes back to home page
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        backHomePage();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JLabel txtProductID;
    private javax.swing.JTextField txtRate;
    private javax.swing.JComboBox<String> txtYes;
    // End of variables declaration//GEN-END:variables
}
