package bnb.billing.system;

import javax.swing.JOptionPane; 

public class homePage extends javax.swing.JFrame {

    public homePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddBuyer = new javax.swing.JButton();
        btnDeleteBuyer = new javax.swing.JButton();
        btnUpdateBuyer = new javax.swing.JButton();
        btnBuyerDets = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnUpdateProd = new javax.swing.JButton();
        btnProductDetails = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddBuyer.setBackground(new java.awt.Color(204, 204, 204));
        btnAddBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addbuyer.png"))); // NOI18N
        btnAddBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 90));

        btnDeleteBuyer.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletebuyer.png"))); // NOI18N
        btnDeleteBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, 90));

        btnUpdateBuyer.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatebuyer.png"))); // NOI18N
        btnUpdateBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBuyerActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 100, 90));

        btnBuyerDets.setBackground(new java.awt.Color(204, 204, 204));
        btnBuyerDets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userdetails.png"))); // NOI18N
        btnBuyerDets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyerDetsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuyerDets, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 90));

        btnAddProduct.setBackground(new java.awt.Color(204, 204, 204));
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addproduct.png"))); // NOI18N
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 110, 90));

        btnUpdateProd.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/udpateproduct.png"))); // NOI18N
        btnUpdateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 90, 90));

        btnProductDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnProductDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proddetails.png"))); // NOI18N
        btnProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 90, 90));

        btnDeleteProduct.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/removeprod.png"))); // NOI18N
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 110, 90));

        btnBilling.setBackground(new java.awt.Color(204, 204, 204));
        btnBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill.png"))); // NOI18N
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        getContentPane().add(btnBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 100, 90));

        btnLogOut.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 90, 90));

        jLabel2.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Buyer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Remove Buyer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Buyer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buyer Details");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Product");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Remove Product");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Billing");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Log Out");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Moche", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Update Product");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // adds action to button when clicked so the designated classes will run
    
    private void btnAddBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBuyerActionPerformed
        new addBuyer().setVisible(true);
    }//GEN-LAST:event_btnAddBuyerActionPerformed

    private void btnUpdateBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBuyerActionPerformed
        new updateBuyer().setVisible(true);
    }//GEN-LAST:event_btnUpdateBuyerActionPerformed

    private void btnUpdateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProdActionPerformed
        new updateProduct().setVisible(true);
    }//GEN-LAST:event_btnUpdateProdActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        new addProduct().setVisible(true);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Are you sure you want to log out?","Select",JOptionPane.YES_NO_OPTION); // pop-up message to confirm logout process
        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBuyerDetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyerDetsActionPerformed
        new buyerDetails().setVisible(true);
    }//GEN-LAST:event_btnBuyerDetsActionPerformed

    private void btnProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductDetailsActionPerformed
        new productDetails().setVisible(true);
    }//GEN-LAST:event_btnProductDetailsActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        new deleteProduct().setVisible(true);
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        new billingPage().setVisible(true);
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnDeleteBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBuyerActionPerformed
        new deleteBuyer().setVisible(true);
    }//GEN-LAST:event_btnDeleteBuyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBuyer;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnBuyerDets;
    private javax.swing.JButton btnDeleteBuyer;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProductDetails;
    private javax.swing.JButton btnUpdateBuyer;
    private javax.swing.JButton btnUpdateProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
